import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { applyRecipe, isRecipe, loadRecipe, parseHerdrPluginInfo, planRecipe, rollbackRecipe, verifyRecipe } from "../src/recipes.js";

const valid={recipeVersion:1,id:"demo",version:"1.0.0",origin:"test",skills:[{id:"demo-skill",source:"skill",targets:["codex"]}],tools:[],prerequisites:[],checks:[],rollback:{managedOnly:true}} as const;
test("recipe validation rejects unsafe paths, unknown agents, private overlays, and duplicate ids",()=>{assert.equal(isRecipe(valid),true);assert.equal(isRecipe({...valid,skills:[valid.skills[0],valid.skills[0]]}),false);assert.equal(isRecipe({...valid,skills:[{...valid.skills[0],source:"../secret"}]}),false);assert.equal(isRecipe({...valid,skills:[{...valid.skills[0],targets:["unknown"]}]}),false);assert.equal(isRecipe({...valid,skills:[{...valid.skills[0],localOverlay:"C:/private"}]}),false);});
test("plan is read-only; apply requires its token, is idempotent, verifiable, and rollback is scoped",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"afd-recipe-"));const home=path.join(dir,"home");const bundle=path.join(dir,"bundle");await mkdir(path.join(bundle,"skill"),{recursive:true});await writeFile(path.join(bundle,"skill","SKILL.md"),"# demo\n");const file=path.join(bundle,"recipe.json");await writeFile(file,JSON.stringify(valid));const plan=await planRecipe(file,home);assert.equal(plan.blocked,false);assert.equal(await readFile(path.join(bundle,"skill","SKILL.md"),"utf8"),"# demo\n");await assert.rejects(applyRecipe(file,{home}),/--confirm/);await assert.rejects(applyRecipe(file,{home,confirm:true,approvalToken:"stale"}),/stale/);await applyRecipe(file,{home,confirm:true,approvalToken:plan.approvalToken});await applyRecipe(file,{home,confirm:true,approvalToken:plan.approvalToken});assert.equal((await verifyRecipe(file,home)).ok,true);const unrelated=path.join(home,"keep.txt");await mkdir(home,{recursive:true});await writeFile(unrelated,"keep");const removed=await rollbackRecipe(file,{home,confirm:true});assert.equal(removed.length,1);assert.equal(await readFile(unrelated,"utf8"),"keep");});
test("verify detects drift and rollback rejects tampered state",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"afd-tamper-"));const home=path.join(dir,"home");const bundle=path.join(dir,"bundle");await mkdir(path.join(bundle,"skill"),{recursive:true});await writeFile(path.join(bundle,"skill","SKILL.md"),"original");const file=path.join(bundle,"recipe.json");await writeFile(file,JSON.stringify(valid));const plan=await planRecipe(file,home);await applyRecipe(file,{home,confirm:true,approvalToken:plan.approvalToken});const target=path.join(home,".agents","skills","demo-skill","SKILL.md");await writeFile(target,"drift");assert.equal((await verifyRecipe(file,home)).drift.length,1);const keep=path.join(home,"keep.txt");await writeFile(keep,"keep");const state=path.join(home,".afd","recipes","demo","applied.json");await writeFile(state,JSON.stringify({managed:[keep]}));await assert.rejects(rollbackRecipe(file,{home,confirm:true}),/Unsafe/);assert.equal(await readFile(keep,"utf8"),"keep");});
test("HTTPS recipe loader fails closed and accepts valid content without redirects",async()=>{const original=globalThis.fetch;try{globalThis.fetch=async()=>new Response("offline",{status:503});await assert.rejects(loadRecipe("https://example.invalid/recipe.json"),/HTTP 503/);globalThis.fetch=async()=>new Response(JSON.stringify({...valid,skills:[]}),{status:200});assert.equal((await loadRecipe("https://example.test/recipe.json")).recipe.id,"demo");}finally{globalThis.fetch=original;}});
test("pinned allowlisted npm tools are planned without becoming arbitrary-script adapters",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"afd-tool-"));const recipe={...valid,skills:[],tools:[{id:"vibium",command:"vibium",source:"npm:vibium",version:"26.8.21",checksum:"sha512-juCBbrm52Y9u4gEascBCQx9fSRQMJr8Pc8+4UmChgR1jkYgIWA8L9mwG/j4WTAOkKC3PdV+Xqy1QYZrEEztcvg=="}]};const file=path.join(dir,"recipe.json");await writeFile(file,JSON.stringify(recipe));const plan=await planRecipe(file,path.join(dir,"home"));assert.equal(plan.blocked,false);assert.equal(plan.actions[0]?.kind,"install-tool");const arbitrary={...recipe,tools:[{...recipe.tools[0],source:"npm:other"}]};await writeFile(file,JSON.stringify(arbitrary));assert.equal((await planRecipe(file,path.join(dir,"home"))).blocked,true);});
test("recipe v2 declares observability as a capability and includes all effects in one token",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"afd-capability-"));const recipe={...valid,recipeVersion:2,skills:[],capabilities:[{id:"observability",required:true,collector:{version:"0.159.0",source:"https://example.test/otelcol.tar.gz",sha256:"a".repeat(64)},phoenix:{version:"20.4.0",lockSha256:"c".repeat(64),runtime:{version:"3.10.21",source:"https://example.test/python.tar.gz",sha256:"e".repeat(64)}},agentacct:{version:"0.10.1",mode:"observe-only",source:"https://example.test/agentacct.whl",sha256:"b".repeat(64),lockSha256:"d".repeat(64)},retentionDays:30,autostart:true,nativeIntegrations:["codex"]}]};const file=path.join(dir,"recipe.json");await writeFile(file,JSON.stringify(recipe));assert.equal(isRecipe(recipe),true);const plan=await planRecipe(file,path.join(dir,"home"));assert.equal(plan.actions[0]?.kind,"configure-capability");assert.match(plan.actions[0]?.detail??"",/CPython 3\.10\.21/);assert.match(plan.actions[0]?.detail??"",/agentacct 0\.10\.1/);assert.match(plan.actions[0]?.detail??"",/Evidence v2 shadow disabled/);const changed={...recipe,capabilities:[{...recipe.capabilities[0],autostart:false}]};await writeFile(file,JSON.stringify(changed));assert.notEqual((await planRecipe(file,path.join(dir,"home"))).approvalToken,plan.approvalToken);});
test("recipe v3 supports an exact mise tool and pinned Herdr plugins",async()=>{const recipe={...valid,recipeVersion:3,skills:[],tools:[{id:"herdr",command:"herdr",version:"0.8.2",installer:{kind:"mise",tool:"github:herdrdev/herdr",scope:"afd-global"},platforms:["windows","linux","macos"]}],plugins:[{id:"example.plugin",host:"herdr",source:"owner/repo/subdir",commit:"a".repeat(40),manifestSha256:"b".repeat(64),enabled:true,platforms:["windows","linux","macos"]}]};assert.equal(isRecipe(recipe),true);assert.equal(isRecipe({...recipe,tools:[{...recipe.tools[0],version:"latest"}]}),false);assert.equal(isRecipe({...recipe,plugins:[{...recipe.plugins[0],commit:"main"}]}),false);assert.equal(isRecipe({...recipe,plugins:[{...recipe.plugins[0],source:"owner/repo/../escape"}]}),false);assert.equal(isRecipe({...recipe,plugins:[recipe.plugins[0],recipe.plugins[0]]}),false);assert.equal(isRecipe({...recipe,integrations:[]}),false);const builtin=await loadRecipe("builtin:herdr-workbench");assert.equal(builtin.recipe.recipeVersion,3);assert.deepEqual(builtin.recipe.tools[0]?.platforms,["windows","linux","macos"]);assert.deepEqual(builtin.recipe.plugins,[]);});
test("Herdr plugin inventory matches the exact plugin object instead of unrelated JSON text",()=>{const output=JSON.stringify({id:"cli:plugin",result:{plugins:[{id:"alpha",source:"owner/alpha",resolved_ref:"a".repeat(40),enabled:true},{id:"beta",source:"owner/beta",resolved_ref:"b".repeat(40),enabled:false}]}});assert.match(parseHerdrPluginInfo(output,"beta")??"",/owner\/beta/);assert.doesNotMatch(parseHerdrPluginInfo(output,"beta")??"",/owner\/alpha/);assert.equal(parseHerdrPluginInfo(output,"missing"),undefined);assert.equal(parseHerdrPluginInfo("not-json","alpha"),undefined);});
