import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import { AgentacctAdapter } from "../src/agentacct-adapter.js";
import type { ObservabilityRecipeCapability } from "../src/contracts.js";
import type { HostCommand, PlatformAdapter } from "../src/platform.js";
import { applyTelemetry, resumeTelemetry, stopTelemetry, telemetryPlan, telemetryStatus, verifyTelemetry } from "../src/telemetry-runtime.js";

const capability:ObservabilityRecipeCapability={id:"observability",required:true,collector:{version:"0.159.0",source:"https://example.test/collector.tar.gz",sha256:"a".repeat(64)},phoenix:{version:"20.4.0",lockSha256:"b2da7e0d3ea17e0cd399127fa63231a99f1415807accfb8fb564449095d7ec3c",runtime:{version:"3.10.21",source:"https://example.test/python.tar.gz",sha256:"e".repeat(64)}},agentacct:{version:"0.10.1",mode:"observe-only",source:"https://example.test/agentacct.whl",sha256:"b".repeat(64),lockSha256:"86f83621d868f9759263c861fde70732d85c0c8821d24b12e6d01ff99558f3ea"},retentionDays:30,autostart:true,nativeIntegrations:[]};
async function fixture(){
  const stateRoot=await mkdtemp(path.join(tmpdir(),"afd-runtime-"));const running=new Set<number>();const ports=new Set<number>();let nextPid=40;const calls:HostCommand[]=[];
  const adapter:PlatformAdapter={
    id:"win32",stateRoot,
    async run(command){
      calls.push(command);
      if(command.executable==="where.exe")return{status:0,stdout:`C:\\tools\\${command.args[0]}.exe\n`,stderr:"",timedOut:false};
      if(command.executable==="whoami.exe")return{status:0,stdout:'"user","S-1-5-21-1"\n',stderr:"",timedOut:false};
      if(command.executable.includes("tar")&&!command.args.includes("--")){const target=command.args[command.args.indexOf("-C")+1];if(target){await mkdir(target,{recursive:true});await writeFile(path.join(target,"otelcol-contrib.exe"),"fixture");}return{status:0,stdout:"",stderr:"",timedOut:false};}
      const joined=command.args.join(" ");
      if(joined.includes("printf %s"))return{status:0,stdout:"/home/test\n",stderr:"",timedOut:false};
      if(joined.includes("command -v uv"))return{status:0,stdout:"/usr/bin/uv\n",stderr:"",timedOut:false};
      if(joined.includes("command -v curl"))return{status:0,stdout:"/usr/bin/curl\n",stderr:"",timedOut:false};
      if(joined.includes("command -v sha256sum"))return{status:0,stdout:"/usr/bin/sha256sum\n",stderr:"",timedOut:false};
      if(joined.includes("command -v tar"))return{status:0,stdout:"/usr/bin/tar\n",stderr:"",timedOut:false};
      if(joined.includes("phoenix-python")&&joined.includes("/usr/bin/sha256sum"))return{status:0,stdout:`${"e".repeat(64)}  runtime\n`,stderr:"",timedOut:false};
      if(joined.includes("/usr/bin/sha256sum"))return{status:0,stdout:`${"b".repeat(64)}  artifact\n`,stderr:"",timedOut:false};
      if(joined.includes("phoenix-python")&&joined.includes("--version"))return{status:0,stdout:"Python 3.10.21\n",stderr:"",timedOut:false};
      if(joined.includes("agentacct --version"))return{status:0,stdout:"agentacct 0.10.1\n",stderr:"",timedOut:false};
      if(joined.includes("capabilities agents --json"))return{status:0,stdout:'{"agents":[]}',stderr:"",timedOut:false};
      if(joined.includes("usage health --json"))return{status:0,stdout:'{"status":"healthy"}',stderr:"",timedOut:false};
      if(joined.includes("status --json"))return{status:0,stdout:'{"schema_version":"agent-chronicle.activation-runtime.v1","state":"running","dashboard_health":"healthy","dashboard_url":"http://127.0.0.1:8765/","watcher":"running"}',stderr:"",timedOut:false};
      return{status:0,stdout:"",stderr:"",timedOut:false};
    },
    async start(command){const pid=++nextPid;running.add(pid);if(command.args.some(arg=>arg.includes("arize-phoenix")))ports.add(6006);else ports.add(4318);return pid;},
    async stop(pid){running.delete(pid);if(pid===41)ports.delete(6006);if(pid===42)ports.delete(4318);},async isRunning(pid){return running.has(pid);},async processFingerprint(pid){return running.has(pid)?"f".repeat(64):undefined;},async isListening(_host,port){return ports.has(port);},async writeText(file,text){await mkdir(path.dirname(file),{recursive:true});await writeFile(file,text);},async readText(file){try{return await readFile(file,"utf8");}catch{return undefined;}},async remove(file){await rm(file,{force:true});},async downloadVerified(_url,target){await mkdir(path.dirname(target),{recursive:true});await writeFile(target,"verified");}
  };
  return{adapter,calls,stateRoot};
}

test("telemetry plan is read-only and expands every recipe-authorized effect",async()=>{const value=await fixture();const plan=telemetryPlan(capability,value.adapter);assert.match(plan.actions.join(" "),/agentacct 0\.10\.1/);assert.match(plan.effects.join(" "),/autostart/);assert.equal(await value.adapter.readText(path.join(value.stateRoot,"telemetry-v2","config.json")),undefined);});
test("telemetry apply, verify and stop manage the three components with one recipe decision",async()=>{const value=await fixture();const agentacct=new AgentacctAdapter(value.adapter,"0.10.1");let emittedTrace="";let emittedPayload="";const dependencies={agentacct,emitTrace:async(trace:Record<string,unknown>)=>{emittedPayload=JSON.stringify(trace);emittedTrace=String((((trace.resourceSpans as Array<Record<string,unknown>>)[0]!.scopeSpans as Array<Record<string,unknown>>)[0]!.spans as Array<Record<string,unknown>>)[0]!.traceId);},fetchJson:async(url:string)=>url.includes(":13133")?{}:{data:[{trace_id:emittedTrace,spans:[{attributes:{"afd.outcome":"ok"}}]}]}};const status=await applyTelemetry(capability,value.adapter,dependencies);assert.equal(status.state,"healthy");const verified=await verifyTelemetry(value.adapter,dependencies);assert.equal(verified.state,"healthy");assert.match(emittedPayload,/AFD_SYNTHETIC_SECRET_DO_NOT_STORE/);assert.deepEqual(verified.diagnostics?.redaction.rejectedCategories,["prompt","response","file-content","command-arguments","stdout","stderr","unknown-attribute"]);assert.equal(verified.diagnostics?.redaction.state,"verified");await assert.rejects(verifyTelemetry(value.adapter,{...dependencies,fetchJson:async(url:string)=>url.includes(":13133")?{}:{data:[{trace_id:emittedTrace,spans:[{attributes:{"afd.outcome":"ok","custom.secret":"AFD_SYNTHETIC_SECRET_DO_NOT_STORE"}}]}]}}),/survived redaction/);const persisted=await value.adapter.readText(path.join(value.stateRoot,"telemetry-v2","verification.json"));assert.doesNotMatch(persisted??"",/AFD_SYNTHETIC_SECRET_DO_NOT_STORE/);const config=await value.adapter.readText(path.join(value.stateRoot,"telemetry-v2","collector","collector.yaml"));assert.match(config??"",/127\.0\.0\.1:4318/);assert.match(config??"",/otlphttp\/phoenix/);assert.match(config??"",/prometheus/);assert.match(config??"",/keep_keys/);assert.match(config??"",/create_directory: true/);assert.doesNotMatch(config??"",/endpoint: https:/);assert.ok(value.calls.some(call=>call.executable==="reg.exe"));await stopTelemetry(value.adapter,{agentacct});});

test("an exact active Codex rotation keeps support declared while exposing the nested retry",async()=>{const value=await fixture();const agentacct=new AgentacctAdapter(value.adapter,"0.10.1");let emittedTrace="";const dependencies={agentacct,emitTrace:async(trace:Record<string,unknown>)=>{emittedTrace=String((((trace.resourceSpans as Array<Record<string,unknown>>)[0]!.scopeSpans as Array<Record<string,unknown>>)[0]!.spans as Array<Record<string,unknown>>)[0]!.traceId);},fetchJson:async(url:string)=>url.includes(":13133")?{}:{data:[{trace_id:emittedTrace,spans:[{attributes:{"afd.outcome":"ok"}}]}]}};await applyTelemetry(capability,value.adapter,dependencies);const originalRun=value.adapter.run.bind(value.adapter);value.adapter.run=async(command)=>{const joined=command.args.join(" ");if(joined.includes("capabilities agents --json"))return{status:0,stdout:'{"clients":[{"client":"codex","capabilities":{"usage_import":{"state":"verified"}}}]}',stderr:"",timedOut:false};if(joined.includes("usage health --json"))return{status:0,stdout:JSON.stringify({schema_version:"agent-chronicle.ingestion-health.v1",state:"degraded",issues:[{source:"codex",code:"source_scan_failed"}],sources:[{source:"codex",state:"degraded",error_code:"codex_rollout_inventory_changed",error_codes:["codex_rollout_inventory_changed"],last_success_at:Date.now()/1_000}]}),stderr:"",timedOut:false};return originalRun(command);};const status=await telemetryStatus(value.adapter,{agentacct});assert.equal(status.state,"healthy");assert.equal(status.capabilities.codex?.sessionImport,"supported");assert.equal((status.agentacct.ingestion as {sources?:Array<{state?:string}>}).sources?.[0]?.state,"degraded");await stopTelemetry(value.adapter,{agentacct});});

test("resume reconciles the declared autostart entry",async()=>{const value=await fixture();const agentacct=new AgentacctAdapter(value.adapter,"0.10.1");let emittedTrace="";const dependencies={agentacct,emitTrace:async(trace:Record<string,unknown>)=>{emittedTrace=String((((trace.resourceSpans as Array<Record<string,unknown>>)[0]!.scopeSpans as Array<Record<string,unknown>>)[0]!.spans as Array<Record<string,unknown>>)[0]!.traceId);},fetchJson:async(url:string)=>url.includes(":13133")?{}:{data:[{trace_id:emittedTrace,spans:[{attributes:{"afd.outcome":"ok"}}]}]}};await applyTelemetry(capability,value.adapter,dependencies);await stopTelemetry(value.adapter,{agentacct});const before=value.calls.filter(call=>call.executable==="reg.exe"&&call.args[0]==="ADD").length;const status=await resumeTelemetry(value.adapter,{agentacct});assert.equal(status.state,"healthy");assert.equal(value.calls.filter(call=>call.executable==="reg.exe"&&call.args[0]==="ADD").length,before+1);});
