import assert from "node:assert/strict";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";
import type { ObservabilityRecipeCapability } from "../src/contracts.js";
import type { PlatformAdapter } from "../src/platform.js";
import { applyNativeIntegrations, nativeIntegrationPreflight, rollbackNativeIntegrations } from "../src/telemetry-integrations.js";

const capability:ObservabilityRecipeCapability={id:"observability",required:true,collector:{version:"0.159.0",source:"https://example.test/collector",sha256:"a".repeat(64)},phoenix:{version:"20.4.0",lockSha256:"c".repeat(64),runtime:{version:"3.10.21",source:"https://example.test/python.tar.gz",sha256:"e".repeat(64)}},agentacct:{version:"0.10.1",mode:"observe-only",source:"https://example.test/agentacct",sha256:"b".repeat(64),lockSha256:"d".repeat(64)},retentionDays:30,autostart:true,nativeIntegrations:["codex","claude-code"]};

test("native integrations are explicit, content-minimal and exactly reversible",async()=>{const root=await mkdtemp(path.join(tmpdir(),"afd-integrations-"));const codex=path.join(root,"codex");const claude=path.join(root,"claude");await mkdir(codex);await mkdir(claude);const codexFile=path.join(codex,"config.toml");const claudeFile=path.join(claude,"settings.json");const codexBefore='model = "gpt-test"\n';const claudeBefore='{\n  "theme": "dark"\n}\n';await writeFile(codexFile,codexBefore);await writeFile(claudeFile,claudeBefore);const previousCodex=process.env.CODEX_HOME;const previousClaude=process.env.CLAUDE_CONFIG_DIR;process.env.CODEX_HOME=codex;process.env.CLAUDE_CONFIG_DIR=claude;const adapter:PlatformAdapter={id:"linux",stateRoot:path.join(root,"state"),async run(){return{status:0,stdout:"",stderr:"",timedOut:false};},async start(){return 1;},async stop(){},async isRunning(){return false;},async processFingerprint(){return undefined;},async isListening(){return false;},async writeText(file,text){await mkdir(path.dirname(file),{recursive:true});await writeFile(file,text);},async readText(file){try{return await readFile(file,"utf8");}catch{return undefined;}},async remove(file){await rm(file,{force:true});},async downloadVerified(){}};try{assert.deepEqual(await nativeIntegrationPreflight(capability,adapter),[]);await applyNativeIntegrations(capability,adapter);const codexAfter=await readFile(codexFile,"utf8");const claudeAfter=await readFile(claudeFile,"utf8");assert.match(codexAfter,/log_user_prompt = false/);assert.doesNotMatch(codexAfter,/https:/);assert.match(claudeAfter,/OTEL_LOGS_EXPORTER.*none/s);assert.doesNotMatch(claudeAfter,/api[-_]?key|authorization|token/i);await rollbackNativeIntegrations(adapter);assert.equal(await readFile(codexFile,"utf8"),codexBefore);assert.equal(await readFile(claudeFile,"utf8"),claudeBefore);}finally{if(previousCodex===undefined)delete process.env.CODEX_HOME;else process.env.CODEX_HOME=previousCodex;if(previousClaude===undefined)delete process.env.CLAUDE_CONFIG_DIR;else process.env.CLAUDE_CONFIG_DIR=previousClaude;await rm(root,{recursive:true,force:true});}});
