import path from "node:path";
import { createHash, randomBytes } from "node:crypto";
import { readFile, rm } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { ObservabilityRecipeCapability } from "./contracts.js";
import type { HostCommand, PlatformAdapter } from "./platform.js";
import { NodePlatformAdapter, fileExists, windowsPathToWsl, writePrivateText } from "./platform.js";
import { installAutostart, uninstallAutostart } from "./autostart.js";
import { AgentacctAdapter, type AgentacctStatus } from "./agentacct-adapter.js";
import { buildOtlpJsonTrace, emitLoopbackOtlpJson, newSpanId, telemetryIdentity } from "./telemetry.js";
import { applyNativeIntegrations, nativeIntegrationEffects, nativeIntegrationPreflight, rollbackNativeIntegrations } from "./telemetry-integrations.js";

export type TelemetryLifecycleMode = "plan" | "apply" | "verify" | "status" | "stop" | "uninstall-autostart";
type ManagedComponent = "phoenix" | "collector";
type ManagedProcess = { readonly schemaVersion: 2; readonly pid: number; readonly startedAt: string; readonly fingerprint: string; readonly command: HostCommand };
type TelemetryConfig = { readonly schemaVersion: 2; readonly capability: ObservabilityRecipeCapability; readonly appliedAt: string };
export interface TelemetryComponentStatus { readonly state: "disabled" | "healthy" | "starting" | "stale" | "external" | "unavailable" | "incompatible" | "degraded"; readonly pid?: number; readonly listening?: boolean; readonly detail: string }
export interface TelemetryDiagnostics { readonly schemaVersion: 1; readonly lastVerifiedAt: string; readonly redaction: { readonly state: "verified"; readonly rejectedCategories: readonly string[] }; readonly performance: { readonly traceFreshnessMs: number; readonly phoenixQueryMs: number } }
export interface TelemetryStatus { readonly schemaVersion: 2; readonly state: "disabled" | "healthy" | "degraded" | "unavailable" | "incompatible"; readonly collector: TelemetryComponentStatus; readonly phoenix: TelemetryComponentStatus; readonly agentacct: AgentacctStatus; readonly retention?: { readonly correlationDays: number; readonly phoenixDays: number; readonly agentacct: "upstream_unbounded" }; readonly diagnostics?: TelemetryDiagnostics; readonly capabilities: Readonly<Record<string, Readonly<Record<string, "supported" | "unsupported" | "unavailable">>>> }
export interface TelemetryPlan { readonly schemaVersion: 2; readonly stateRoot: string; readonly required: boolean; readonly actions: readonly string[]; readonly effects: readonly string[]; readonly dataBoundary: readonly string[]; readonly capability: ObservabilityRecipeCapability }
export interface TelemetryPreflight { readonly ok: boolean; readonly issues: readonly string[] }
export interface TelemetryDependencies { readonly agentacct?: AgentacctAdapter; readonly fetchJson?: (url:string)=>Promise<unknown>; readonly emitTrace?: (trace:Record<string,unknown>)=>Promise<void> }

const PORTS: Readonly<Record<ManagedComponent, number>> = { phoenix: 6006, collector: 4318 };
function root(adapter: PlatformAdapter): string { return path.join(adapter.stateRoot, "telemetry-v2"); }
function stateFile(adapter: PlatformAdapter, component: ManagedComponent): string { return path.join(root(adapter), component, "process.json"); }
function configFile(adapter: PlatformAdapter): string { return path.join(root(adapter), "config.json"); }
function collectorConfigFile(adapter: PlatformAdapter): string { return path.join(root(adapter), "collector", "collector.yaml"); }
function diagnosticsFile(adapter: PlatformAdapter): string { return path.join(root(adapter), "verification.json"); }
function dependencyLockPath(name: "agentacct" | "phoenix"): string { const current=path.dirname(fileURLToPath(import.meta.url));const candidates=[path.resolve(current,"..","..","requirements",`pylock.${name}.toml`),path.resolve(current,"..","..","..","requirements",`pylock.${name}.toml`)];const found=candidates.find(existsSync);if(!found)throw new Error(`AFD ${name} dependency lock is missing.`);return found; }
async function verifyPhoenixLock(capability: ObservabilityRecipeCapability): Promise<string> { const file=dependencyLockPath("phoenix");const actual=createHash("sha256").update(await readFile(file)).digest("hex");if(actual!==capability.phoenix.lockSha256.toLowerCase())throw new Error("The Phoenix dependency lock does not match the reviewed recipe.");return file; }
async function verifyAgentacctLock(capability: ObservabilityRecipeCapability): Promise<string> { const file=dependencyLockPath("agentacct");const actual=createHash("sha256").update(await readFile(file)).digest("hex");if(actual!==capability.agentacct.lockSha256.toLowerCase())throw new Error("The agentacct dependency lock does not match the reviewed recipe.");return file; }
async function ensureIdentityKey(adapter: PlatformAdapter): Promise<void> { const file=path.join(root(adapter),"identity.key");const existing=await adapter.readText(file);if(existing){if(!/^[a-f0-9]{64}\s*$/.test(existing))throw new Error("Telemetry identity key is invalid.");return;}await writePrivateText(adapter,file,randomBytes(32).toString("hex")+"\n"); }
async function wslPath(adapter:PlatformAdapter,value:string):Promise<string>{if(adapter.id!=="win32")throw new Error("WSL path translation is Windows-only.");return windowsPathToWsl(value);}
async function wslExecutable(adapter:PlatformAdapter,name:string):Promise<string>{if(!/^[a-z0-9._-]+$/i.test(name))throw new Error("Invalid WSL command name.");const result=await adapter.run({executable:"wsl.exe",args:["--","sh","-lc",`command -v ${name}`],timeoutMs:10_000});const value=result.stdout.trim();if(result.status!==0||!value.startsWith("/"))throw new Error(`Required WSL command is unavailable: ${name}.`);return value;}
async function wslHome(adapter:PlatformAdapter):Promise<string>{if(adapter.id!=="win32")throw new Error("WSL home resolution is Windows-only.");const result=await adapter.run({executable:"wsl.exe",args:["--","sh","-lc",'printf %s "$HOME"'],timeoutMs:10_000});const home=result.stdout.trim();if(result.status!==0||!/^\/home\/[A-Za-z0-9._-]+$/.test(home))throw new Error("Could not resolve a safe WSL home for the Phoenix runtime.");return home;}
async function phoenixPythonRoot(adapter:PlatformAdapter,capability:ObservabilityRecipeCapability):Promise<string>{const runtime=capability.phoenix.runtime;exactVersion(runtime.version,"Phoenix Python runtime");if(!/^https:\/\//i.test(runtime.source)||!/^[a-f0-9]{64}$/i.test(runtime.sha256))throw new Error("Phoenix Python runtime requires an HTTPS source and SHA-256.");return `${await wslHome(adapter)}/.local/share/afd/telemetry-v2/phoenix-python-${runtime.version}-${runtime.sha256.slice(0,12).toLowerCase()}`;}
function phoenixPythonExecutable(rootPath:string):string{return `${rootPath}/bin/python3.10`;}
async function probePhoenixPython(adapter:PlatformAdapter,executable:string,version:string):Promise<boolean>{const exists=await adapter.run({executable:"wsl.exe",args:["--","test","-x",executable],timeoutMs:10_000});if(exists.status!==0)return false;const result=await adapter.run({executable:"wsl.exe",args:["--",executable,"--version"],timeoutMs:10_000});return result.status===0&&result.stdout.trim()===`Python ${version}`;}
async function installPhoenixPython(adapter:PlatformAdapter,capability:ObservabilityRecipeCapability):Promise<string>{
  if(adapter.id!=="win32")throw new Error("The pinned Phoenix runtime is currently implemented for Windows via WSL only.");
  const runtime=capability.phoenix.runtime;const finalRoot=await phoenixPythonRoot(adapter,capability);const executable=phoenixPythonExecutable(finalRoot);if(await probePhoenixPython(adapter,executable,runtime.version))return executable;
  const staging=`${finalRoot}.staging`;const archive=`${staging}/runtime.tar.gz`;if(!/^\/home\/[A-Za-z0-9._-]+\/\.local\/share\/afd\/telemetry-v2\/phoenix-python-[0-9.]+-[a-f0-9]{12}(?:\.staging)?$/.test(staging))throw new Error("Unsafe AFD-managed Phoenix runtime root.");
  const remove=async(target:string)=>adapter.run({executable:"wsl.exe",args:["--","/usr/bin/rm","-rf","--",target],timeoutMs:60_000});await remove(staging);await remove(finalRoot);
  const mkdirResult=await adapter.run({executable:"wsl.exe",args:["--","/usr/bin/mkdir","-p","--",staging],timeoutMs:10_000});if(mkdirResult.status!==0)throw new Error("Could not create the AFD-managed Phoenix runtime root.");
  try{
    const curl=await wslExecutable(adapter,"curl");const downloaded=await adapter.run({executable:"wsl.exe",args:["--",curl,"-fsSL",runtime.source,"-o",archive],timeoutMs:180_000});if(downloaded.status!==0||downloaded.timedOut)throw new Error("Pinned Phoenix Python runtime download failed.");
    const sha=await wslExecutable(adapter,"sha256sum");const digest=await adapter.run({executable:"wsl.exe",args:["--",sha,archive],timeoutMs:30_000});if(digest.status!==0||digest.stdout.trim().split(/\s+/)[0]?.toLowerCase()!==runtime.sha256.toLowerCase())throw new Error("Phoenix Python runtime SHA-256 mismatch.");
    const tar=await wslExecutable(adapter,"tar");const extracted=await adapter.run({executable:"wsl.exe",args:["--",tar,"-xzf",archive,"-C",staging,"--strip-components=1"],timeoutMs:120_000});if(extracted.status!==0||extracted.timedOut)throw new Error("Verified Phoenix Python runtime extraction failed.");await adapter.run({executable:"wsl.exe",args:["--","/usr/bin/rm","-f","--",archive],timeoutMs:10_000});
    const stagingExecutable=phoenixPythonExecutable(staging);if(!await probePhoenixPython(adapter,stagingExecutable,runtime.version))throw new Error("Verified Phoenix Python runtime has an incompatible executable.");const moved=await adapter.run({executable:"wsl.exe",args:["--","/usr/bin/mv","--",staging,finalRoot],timeoutMs:30_000});if(moved.status!==0)throw new Error("Could not activate the verified Phoenix Python runtime.");if(!await probePhoenixPython(adapter,executable,runtime.version))throw new Error("Activated Phoenix Python runtime failed its version probe.");return executable;
  }catch(error){await remove(staging);await remove(finalRoot);throw error;}
}
async function requirePhoenixPython(adapter:PlatformAdapter,capability:ObservabilityRecipeCapability):Promise<string>{const rootPath=await phoenixPythonRoot(adapter,capability);const executable=phoenixPythonExecutable(rootPath);if(!await probePhoenixPython(adapter,executable,capability.phoenix.runtime.version))throw new Error("Pinned Phoenix Python runtime is missing or incompatible; reapply the recipe.");return executable;}
async function removePhoenixPython(adapter:PlatformAdapter,capability:ObservabilityRecipeCapability):Promise<void>{if(adapter.id!=="win32")return;const rootPath=await phoenixPythonRoot(adapter,capability);if(!/^\/home\/[A-Za-z0-9._-]+\/\.local\/share\/afd\/telemetry-v2\/phoenix-python-[0-9.]+-[a-f0-9]{12}$/.test(rootPath))throw new Error("Unsafe AFD-managed Phoenix runtime root.");const result=await adapter.run({executable:"wsl.exe",args:["--","/usr/bin/rm","-rf","--",rootPath,`${rootPath}.staging`],timeoutMs:60_000});if(result.status!==0)throw new Error("Could not remove the AFD-managed Phoenix runtime.");}
function exactVersion(value: string, component: string): string { if (!/^\d+\.\d+\.\d+$/.test(value)) throw new Error(`An exact ${component} version is required.`); return value; }
function yamlString(value: string): string { return JSON.stringify(value); }

export function telemetryPlan(capability: ObservabilityRecipeCapability, adapter: PlatformAdapter = new NodePlatformAdapter()): TelemetryPlan {
  exactVersion(capability.collector.version, "Collector"); exactVersion(capability.phoenix.version, "Phoenix"); exactVersion(capability.agentacct.version, "agentacct");
  return {
    schemaVersion: 2, stateRoot: root(adapter), required: capability.required, capability,
    actions: [
      `Download and verify OpenTelemetry Collector ${capability.collector.version} with SHA-256 ${capability.collector.sha256}.`,
      `Configure loopback OTLP/HTTP 127.0.0.1:4318 and route traces to Phoenix 127.0.0.1:6006.`,
      `Start Arize Phoenix ${capability.phoenix.version} with ${capability.retentionDays}-day retention.`,
      `Download and verify CPython ${capability.phoenix.runtime.version} with SHA-256 ${capability.phoenix.runtime.sha256} for the isolated Phoenix runtime.`,
      `Install agentacct ${capability.agentacct.version} in an AFD-isolated environment, keep its unstable Evidence v2 shadow disabled, and import supported local stores read-only.`,
      "Start the agentacct watcher and local dashboard on 127.0.0.1:8765.",
      `Probe capabilities independently for ${capability.nativeIntegrations.join(", ") || "no agents"}.`,
      capability.autostart ? "Install declared current-user autostart entries." : "Leave autostart disabled.",
    ],
    effects: [root(adapter), `AFD-managed WSL CPython ${capability.phoenix.runtime.version} for Phoenix`, ...nativeIntegrationEffects(capability), "read-only access to supported local agent session stores", "agentacct local evidence store", "agentacct loopback dashboard 127.0.0.1:8765", ...(capability.autostart ? ["current-user AFD telemetry supervisor autostart entry"] : [])],
    dataBoundary: ["loopback listeners only", "no remote exporters", "no prompt/response/file/argv/stdout/stderr in AFD telemetry", "agentacct source evidence remains in its own local v1 store", "agentacct Evidence v2 shadow disabled", "agentacct retention is upstream_unbounded", "pricing auto-refresh disabled"],
  };
}

export async function telemetryPreflight(capability: ObservabilityRecipeCapability, adapter: PlatformAdapter = new NodePlatformAdapter()): Promise<TelemetryPreflight> {
  const issues:string[]=[]; try { telemetryPlan(capability,adapter); } catch(error) { issues.push(error instanceof Error?error.message:String(error)); }
  for(const verify of [verifyPhoenixLock,verifyAgentacctLock])try{await verify(capability);}catch(error){issues.push(error instanceof Error?error.message:String(error));}
  if(adapter.id!=="win32")issues.push("The built-in Observability recipe currently pins a Windows x64 Collector artifact.");
  if(adapter.id==="win32"){const wsl=await adapter.run({executable:"wsl.exe",args:["--status"],timeoutMs:10_000});if(wsl.status!==0||wsl.timedOut)issues.push("WSL is unavailable to host the supported agentacct runtime.");else{const uv=await adapter.run({executable:"wsl.exe",args:["--","sh","-lc","command -v uv >/dev/null && python3 -c 'import sys; raise SystemExit(sys.version_info < (3,11))'"],timeoutMs:10_000});if(uv.status!==0||uv.timedOut)issues.push("WSL requires uv and Python 3.11 or newer for agentacct.");const namespace=await adapter.run({executable:"wsl.exe",args:["--exec","unshare","--user","--map-root-user","--mount","/usr/bin/true"],timeoutMs:10_000});if(namespace.status!==0||namespace.timedOut)issues.push("WSL must allow an unprivileged read-only mount namespace for Codex session import.");}}
  for(const component of ["phoenix","collector"] as const){const state=await processState(adapter,component);if(state.state==="external"||state.state==="starting")issues.push(`${component}: ${state.detail}`);}
  for(const port of [13133,9464,8765])if(await adapter.isListening("127.0.0.1",port))issues.push(`loopback port ${port} is already in use.`);
  issues.push(...await nativeIntegrationPreflight(capability,adapter));
  return{ok:issues.length===0,issues};
}

function collectorYaml(adapter: PlatformAdapter): string {
  const queue = path.join(root(adapter), "collector", "queue");
  // Escaped quotes are intentional YAML content inside this template literal.
  // eslint-disable-next-line no-useless-escape
  return `extensions:\n  health_check:\n    endpoint: 127.0.0.1:13133\n  file_storage:\n    directory: ${yamlString(queue)}\n    create_directory: true\nreceivers:\n  otlp:\n    protocols:\n      http:\n        endpoint: 127.0.0.1:4318\n  hostmetrics:\n    collection_interval: 30s\n    scrapers:\n      cpu: {}\n      memory: {}\n      disk: {}\n      filesystem: {}\n      network: {}\nprocessors:\n  memory_limiter:\n    check_interval: 1s\n    limit_mib: 128\n    spike_limit_mib: 32\n  filter/privacy:\n    error_mode: propagate\n    traces:\n      span:\n        - 'span.attributes[\"afd.schema.version\"] != 2 and resource.attributes[\"service.name\"] != \"claude-code\" and resource.attributes[\"service.name\"] != \"codex_cli_rs\"'\n        - 'Len(span.links) > 0'\n      spanevent:\n        - 'true'\n  transform/privacy:\n    error_mode: propagate\n    trace_statements:\n      - context: resource\n        statements:\n          - keep_keys(resource.attributes, [\"service.name\", \"openinference.project.name\"])\n      - context: span\n        statements:\n          - keep_keys(span.attributes, [\"afd.schema.version\", \"afd.project.id\", \"afd.workspace.id\", \"afd.run.id\", \"afd.agent.name\", \"afd.operation\", \"afd.outcome\", \"gen_ai.operation.name\", \"gen_ai.request.model\", \"error.type\"])\n  batch: {}\nexporters:\n  otlphttp/phoenix:\n    endpoint: http://127.0.0.1:6006\n    sending_queue:\n      enabled: true\n      storage: file_storage\n      queue_size: 2048\n    retry_on_failure:\n      enabled: true\n      max_elapsed_time: 24h\n  prometheus:\n    endpoint: 127.0.0.1:9464\nservice:\n  extensions: [health_check, file_storage]\n  pipelines:\n    traces:\n      receivers: [otlp]\n      processors: [memory_limiter, filter/privacy, transform/privacy, batch]\n      exporters: [otlphttp/phoenix]\n    metrics:\n      receivers: [hostmetrics]\n      processors: [memory_limiter, batch]\n      exporters: [prometheus]\n`;
}

async function resolveCommand(adapter: PlatformAdapter, name: string): Promise<string> {
  const query = adapter.id === "win32" ? { executable: "where.exe", args: [name], timeoutMs: 5_000 } : { executable: "which", args: [name], timeoutMs: 5_000 };
  const result = await adapter.run(query); const value = result.stdout.split(/\r?\n/).map((line) => line.trim()).find(Boolean);
  if (result.status !== 0 || result.timedOut || !value) throw new Error(`Required command is not executable: ${name}.`); return value;
}
async function collectorExecutable(adapter: PlatformAdapter, capability: ObservabilityRecipeCapability): Promise<string> {
  const toolRoot = path.join(root(adapter), "tools", `otelcol-contrib-${capability.collector.version}-${capability.collector.sha256.slice(0, 12).toLowerCase()}`); const names = adapter.id === "win32" ? ["otelcol-contrib.exe", "otelcol.exe"] : ["otelcol-contrib", "otelcol"];
  for (const name of names) { const candidate = path.join(toolRoot, name); if (await fileExists(candidate)) return candidate; }
  const archive = path.join(root(adapter), "downloads", `otelcol-${capability.collector.version}-${capability.collector.sha256.slice(0, 12)}.archive`);
  await adapter.downloadVerified(capability.collector.source, archive, capability.collector.sha256); await adapter.writeText(path.join(toolRoot, ".afd-root"), "managed\n");
  const tar = await resolveCommand(adapter, "tar"); const unpack = await adapter.run({ executable: tar, args: ["-xf", archive, "-C", toolRoot], timeoutMs: 60_000 }); if (unpack.status !== 0) throw new Error("Verified Collector archive extraction failed.");
  for (const name of names) { const candidate = path.join(toolRoot, name); if (await fileExists(candidate)) return candidate; } throw new Error("Verified Collector archive lacks a supported executable.");
}
async function readManaged(adapter: PlatformAdapter, component: ManagedComponent): Promise<ManagedProcess | undefined> { const raw = await adapter.readText(stateFile(adapter, component)); if (!raw) return undefined; try { const value = JSON.parse(raw) as Partial<ManagedProcess>; return value.schemaVersion === 2 && Number.isSafeInteger(value.pid) && Number(value.pid) > 0 && typeof value.fingerprint === "string" && /^[a-f0-9]{64}$/.test(value.fingerprint) && value.command && typeof value.command.executable === "string" ? value as ManagedProcess : undefined; } catch { return undefined; } }
async function processState(adapter: PlatformAdapter, component: ManagedComponent): Promise<TelemetryComponentStatus & { readonly managed?: ManagedProcess }> { const managed = await readManaged(adapter, component); const listening = await adapter.isListening("127.0.0.1", PORTS[component]); if (!managed) return listening ? { state: "external", listening, detail: `loopback port ${PORTS[component]} is not owned by telemetry-v2` } : { state: "disabled", listening, detail: "not configured" }; const running = await adapter.isRunning(managed.pid); const fingerprint = running ? await adapter.processFingerprint(managed.pid) : undefined; const owned = fingerprint === managed.fingerprint; if (owned && listening) return { state: "healthy", pid: managed.pid, listening, detail: "AFD-managed process is ready", managed }; if (owned) return { state: "starting", pid: managed.pid, listening, detail: "process is alive but not ready", managed }; if (running) return { state: "external", pid: managed.pid, listening, detail: "recorded PID belongs to another process instance", managed }; return { state: "stale", pid: managed.pid, listening, detail: "managed process is not running", managed }; }
async function startManaged(adapter: PlatformAdapter, component: ManagedComponent, command: HostCommand): Promise<void> { const current = await processState(adapter, component); if (current.state === "healthy") return; if (current.state === "external" || current.state === "starting") throw new Error(`${component} cannot start: ${current.detail}.`); const pid = await adapter.start(command); const fingerprint = await adapter.processFingerprint(pid); if (!fingerprint) { await adapter.stop(pid); throw new Error(`Could not fingerprint ${component}; its process tree was stopped.`); } const record: ManagedProcess = { schemaVersion: 2, pid, startedAt: new Date().toISOString(), fingerprint, command }; await adapter.writeText(stateFile(adapter, component), JSON.stringify(record) + "\n"); const attempts=component==="phoenix"?120:40;for (let index = 0; index < attempts; index += 1) { if (await adapter.isListening("127.0.0.1", PORTS[component])) return; await new Promise((resolve) => setTimeout(resolve, 500)); } await adapter.stop(pid); await adapter.remove(stateFile(adapter, component)); throw new Error(`${component} failed to become ready on loopback.`); }
async function stopManaged(adapter: PlatformAdapter, component: ManagedComponent): Promise<void> { const current = await processState(adapter, component); if (!current.managed) return; if (current.state === "external") throw new Error(`${component} state no longer owns its recorded process; stop refused.`); if (current.state === "healthy" || current.state === "starting") await adapter.stop(current.managed.pid); if (await adapter.isRunning(current.managed.pid)) throw new Error(`${component} process tree is still running.`); await adapter.remove(stateFile(adapter, component)); }
async function readConfig(adapter: PlatformAdapter): Promise<TelemetryConfig | undefined> { const raw = await adapter.readText(configFile(adapter)); if (!raw) return undefined; try { const value = JSON.parse(raw) as TelemetryConfig; return value.schemaVersion === 2 && value.capability?.id === "observability" ? value : undefined; } catch { return undefined; } }
const REJECTED_ATTRIBUTE_CATEGORIES = ["prompt", "response", "file-content", "command-arguments", "stdout", "stderr", "unknown-attribute"] as const;
const PRIVACY_CANARY = "AFD_SYNTHETIC_SECRET_DO_NOT_STORE";
function finiteDuration(value:unknown):value is number{return typeof value==="number"&&Number.isFinite(value)&&value>=0&&value<=86_400_000;}
async function readDiagnostics(adapter:PlatformAdapter):Promise<TelemetryDiagnostics|undefined>{const raw=await adapter.readText(diagnosticsFile(adapter));if(!raw)return undefined;try{const value=JSON.parse(raw) as Partial<TelemetryDiagnostics>;const categories=value.redaction?.rejectedCategories;return value.schemaVersion===1&&typeof value.lastVerifiedAt==="string"&&!Number.isNaN(Date.parse(value.lastVerifiedAt))&&value.redaction?.state==="verified"&&Array.isArray(categories)&&categories.every(category=>REJECTED_ATTRIBUTE_CATEGORIES.includes(category as typeof REJECTED_ATTRIBUTE_CATEGORIES[number]))&&finiteDuration(value.performance?.traceFreshnessMs)&&finiteDuration(value.performance?.phoenixQueryMs)?value as TelemetryDiagnostics:undefined;}catch{return undefined;}}
function addSyntheticPrivacyCanaries(trace:Record<string,unknown>):void{const resourceSpans=trace.resourceSpans as Array<Record<string,unknown>>;const resource=resourceSpans[0]?.resource as Record<string,unknown>|undefined;const scopeSpans=resourceSpans[0]?.scopeSpans as Array<Record<string,unknown>>|undefined;const spans=scopeSpans?.[0]?.spans as Array<Record<string,unknown>>|undefined;const span=spans?.[0];if(!resource||!span)throw new Error("Synthetic trace shape is invalid.");const resourceAttributes=resource.attributes as Array<Record<string,unknown>>;const spanAttributes=span.attributes as Array<Record<string,unknown>>;resourceAttributes.push({key:"user.home",value:{stringValue:PRIVACY_CANARY}});for(const key of ["prompt","response","file.content","process.command_args","stdout","stderr","custom.secret"])spanAttributes.push({key,value:{stringValue:PRIVACY_CANARY}});span.events=[{name:"forbidden-event",timeUnixNano:span.startTimeUnixNano,attributes:[{key:"content",value:{stringValue:PRIVACY_CANARY}}]}];}
function sessionImportState(agent:string,status:AgentacctStatus):"supported"|"unsupported"|"unavailable" { if(["disabled","unavailable","incompatible"].includes(status.state))return status.state==="disabled"?"unsupported":"unavailable";const manifest=status.capabilities;if(!manifest||typeof manifest!=="object")return"unavailable";const clients=(manifest as Record<string,unknown>).clients;if(!Array.isArray(clients))return"unavailable";const row=clients.find(item=>item&&typeof item==="object"&&(item as Record<string,unknown>).client===agent) as Record<string,unknown>|undefined;if(!row)return"unsupported";const capabilities=row.capabilities&&typeof row.capabilities==="object"?row.capabilities as Record<string,unknown>:{};const usage=capabilities.usage_import&&typeof capabilities.usage_import==="object"?capabilities.usage_import as Record<string,unknown>:{};if(!["verified","verified_partial"].includes(String(usage.state)))return"unavailable";const health=status.ingestion&&typeof status.ingestion==="object"?status.ingestion as Record<string,unknown>:{};const sources=Array.isArray(health.sources)?health.sources:[];const source=sources.find(item=>item&&typeof item==="object"&&(item as Record<string,unknown>).source===agent) as Record<string,unknown>|undefined;return source&&source.state!=="healthy"&&status.state!=="healthy"?"unavailable":"supported"; }
function capabilityMatrix(capability: ObservabilityRecipeCapability | undefined, agentacct: AgentacctStatus): TelemetryStatus["capabilities"] { return Object.fromEntries(["claude-code", "codex", "antigravity", "pi", "hermes"].map((agent) => [agent, { liveTrace: capability?.nativeIntegrations.includes(agent as never) ? "supported" : "unsupported", sessionImport: sessionImportState(agent,agentacct) }])) as TelemetryStatus["capabilities"]; }

function publicAgentacctStatus(status:AgentacctStatus):AgentacctStatus {
  const health=status.ingestion&&typeof status.ingestion==="object"?status.ingestion as Record<string,unknown>:{};
  const sources=Array.isArray(health.sources)?health.sources.filter((item):item is Record<string,unknown>=>Boolean(item)&&typeof item==="object").map((item)=>({
    source:boundedStatusText(item.source),
    state:boundedStatusText(item.state),
    ...(boundedStatusText(item.error_code)?{errorCode:boundedStatusText(item.error_code)}:{}),
    ...(unixSecondsIso(item.last_success_at)?{lastSuccessAt:unixSecondsIso(item.last_success_at)}:{}),
    ...(boundedCount(item.observed_sessions)!==undefined?{observedSessions:boundedCount(item.observed_sessions)}:{}),
    ...(boundedCount(item.usage_sessions)!==undefined?{usageSessions:boundedCount(item.usage_sessions)}:{}),
    ...(boundedCount(item.sessions_without_usage)!==undefined?{sessionsWithoutUsage:boundedCount(item.sessions_without_usage)}:{}),
    ...(boundedCount(item.consecutive_failures)!==undefined?{consecutiveFailures:boundedCount(item.consecutive_failures)}:{}),
  })):[];
  const watcher=health.watcher&&typeof health.watcher==="object"?health.watcher as Record<string,unknown>:{};
  return{state:status.state,...(status.version?{version:status.version}:{}),detail:status.detail,...(status.runtime?{runtime:status.runtime}:{}),...(Object.keys(health).length?{ingestion:{state:boundedStatusText(health.state)??"unknown",...(unixSecondsIso(health.last_success_at)?{lastSuccessAt:unixSecondsIso(health.last_success_at)}:{}),watcher:{state:boundedStatusText(watcher.state)??"unknown",...(unixSecondsIso(watcher.heartbeat_at)?{heartbeatAt:unixSecondsIso(watcher.heartbeat_at)}:{}),...(boundedCount(watcher.interval_seconds)!==undefined?{intervalSeconds:boundedCount(watcher.interval_seconds)}:{})},sources}}:{})};
}
function boundedStatusText(value:unknown):string|undefined{return typeof value==="string"&&value.length<=80?value:undefined;}
function boundedCount(value:unknown):number|undefined{return typeof value==="number"&&Number.isFinite(value)&&value>=0&&value<=Number.MAX_SAFE_INTEGER?value:undefined;}
function unixSecondsIso(value:unknown):string|undefined{if(typeof value!=="number"||!Number.isFinite(value)||value<0)return undefined;const milliseconds=value*1000;if(!Number.isFinite(milliseconds))return undefined;try{return new Date(milliseconds).toISOString();}catch{return undefined;}}
function publicComponentStatus(status:TelemetryComponentStatus):TelemetryComponentStatus{return{state:status.state,...(status.pid?{pid:status.pid}:{}),...(status.listening!==undefined?{listening:status.listening}:{}),detail:status.detail};}

export async function telemetryStatus(adapter: PlatformAdapter = new NodePlatformAdapter(), dependencies: TelemetryDependencies = {}): Promise<TelemetryStatus> {
  const config = await readConfig(adapter); const collector = await processState(adapter, "collector"); const phoenix = await processState(adapter, "phoenix"); const probedAgentacct = config ? await (dependencies.agentacct ?? new AgentacctAdapter(adapter, config.capability.agentacct.version)).status() : { state: "disabled" as const, detail: "not configured" };const diagnostics=config?await readDiagnostics(adapter):undefined;
  const states = [collector.state, phoenix.state, probedAgentacct.state]; const state: TelemetryStatus["state"] = !config ? "disabled" : states.includes("incompatible") ? "incompatible" : states.every((value) => value === "healthy") ? "healthy" : states.includes("unavailable") ? "unavailable" : "degraded";
  return { schemaVersion: 2, state, collector:publicComponentStatus(collector), phoenix:publicComponentStatus(phoenix), agentacct:publicAgentacctStatus(probedAgentacct), ...(config ? { retention:{correlationDays:config.capability.retentionDays,phoenixDays:config.capability.retentionDays,agentacct:"upstream_unbounded" as const} } : {}),...(diagnostics?{diagnostics}:{}), capabilities: capabilityMatrix(config?.capability, probedAgentacct) };
}

async function waitForHealthyTelemetry(adapter:PlatformAdapter,agentacct:AgentacctAdapter,timeoutMs=120_000):Promise<TelemetryStatus>{
  const deadline=Date.now()+timeoutMs;
  let last:TelemetryStatus|undefined;
  do {
    last=await telemetryStatus(adapter,{agentacct});
    if(last.state==="healthy")return last;
    if(last.state==="incompatible")break;
    const remaining=deadline-Date.now();
    if(remaining>0)await new Promise(resolve=>setTimeout(resolve,Math.min(3_000,remaining)));
  } while(Date.now()<deadline);
  const status=last??await telemetryStatus(adapter,{agentacct});
  throw new Error(`Required telemetry capability is ${status.state}: collector=${status.collector.state}; phoenix=${status.phoenix.state}; agentacct=${status.agentacct.state} (${status.agentacct.detail}).`);
}

export async function applyTelemetry(capability: ObservabilityRecipeCapability, adapter: PlatformAdapter = new NodePlatformAdapter(), dependencies: TelemetryDependencies = {}): Promise<TelemetryStatus> {
  const preflight=await telemetryPreflight(capability,adapter);if(!preflight.ok)throw new Error("Telemetry preflight failed before writes: "+preflight.issues.join("; ")); const phoenixVersion = exactVersion(capability.phoenix.version, "Phoenix"); const componentRoot = root(adapter); const collector = await collectorExecutable(adapter, capability); await adapter.writeText(collectorConfigFile(adapter), collectorYaml(adapter)); const validated = await adapter.run({ executable: collector, args: ["validate", "--config", collectorConfigFile(adapter)], timeoutMs: 15_000 }); if (validated.status !== 0) throw new Error("Collector configuration validation failed: " + (validated.stderr || validated.stdout).trim());
  const phoenixData=await wslPath(adapter,path.join(componentRoot,"phoenix","data"));const wslUv=await wslExecutable(adapter,"uv");const phoenixLock=windowsPathToWsl(await verifyPhoenixLock(capability));const phoenixPython=await installPhoenixPython(adapter,capability);const phoenixCommand: HostCommand = { executable:"wsl.exe",args:["--","env",`PHOENIX_WORKING_DIR=${phoenixData}`,"PHOENIX_TELEMETRY_ENABLED=false","PHOENIX_ALLOW_EXTERNAL_RESOURCES=false",`PHOENIX_DEFAULT_RETENTION_POLICY_DAYS=${capability.retentionDays}`,"PHOENIX_ALLOWED_PROVIDERS=NONE","PHOENIX_ALLOWED_SANDBOX_PROVIDERS=NONE",wslUv,"tool","run","--python",phoenixPython,"--no-python-downloads","--from",`arize-phoenix==${phoenixVersion}`,"--with-requirements",phoenixLock,"phoenix","serve","--host","127.0.0.1","--port","6006"] };
  const collectorCommand: HostCommand = { executable: collector, args: ["--config", collectorConfigFile(adapter)], cwd: path.join(componentRoot, "collector") };
  const agentacct = dependencies.agentacct ?? new AgentacctAdapter(adapter, capability.agentacct.version); const agentacctArtifact = path.join(path.dirname(adapter.stateRoot), "afd-telemetry-downloads", `agentacct-${capability.agentacct.version}-py3-none-any.whl`); if(adapter.id!=="win32")await adapter.downloadVerified(capability.agentacct.source, agentacctArtifact, capability.agentacct.sha256);
  const hadConfig=Boolean(await readConfig(adapter));
  try {
    await ensureIdentityKey(adapter);
    await startManaged(adapter, "phoenix", phoenixCommand); await startManaged(adapter, "collector", collectorCommand);
    await agentacct.install({source:capability.agentacct.source,sha256:capability.agentacct.sha256,lockSha256:capability.agentacct.lockSha256,...(adapter.id!=="win32"?{verifiedArtifact:agentacctArtifact}:{})});await adapter.remove(agentacctArtifact); await agentacct.refresh(); await agentacct.start();
    await adapter.writeText(configFile(adapter), JSON.stringify({ schemaVersion: 2, capability, appliedAt: new Date().toISOString() } satisfies TelemetryConfig, null, 2) + "\n");
    if (capability.autostart) { const cli=fileURLToPath(new URL("./cli.js",import.meta.url));await installAutostart(adapter,"telemetry-v2-supervisor",{executable:process.execPath,args:[cli,"telemetry","resume"]}); }
    await waitForHealthyTelemetry(adapter,agentacct);const verified=await verifyTelemetry(adapter,{...dependencies,agentacct});await applyNativeIntegrations(capability,adapter);return verified;
  } catch (error) {
    await adapter.remove(agentacctArtifact).catch(()=>undefined);await rollbackNativeIntegrations(adapter).catch(()=>undefined);await uninstallAutostart(adapter,"telemetry-v2-supervisor").catch(()=>undefined);await agentacct.stop().catch(()=>undefined);await agentacct.uninstallManagedRuntime().catch(()=>undefined);await stopManaged(adapter, "collector").catch(() => undefined);await stopManaged(adapter, "phoenix").catch(() => undefined);
    if(!hadConfig){await removePhoenixPython(adapter,capability).catch(()=>undefined);const managedRoot=path.resolve(root(adapter));const stateRoot=path.resolve(adapter.stateRoot);if(managedRoot.startsWith(stateRoot+path.sep)){await rm(managedRoot,{recursive:true,force:true}).catch(()=>undefined);await new Promise(resolve=>setTimeout(resolve,1_000));await rm(managedRoot,{recursive:true,force:true}).catch(()=>undefined);}}
    throw error;
  }
}

export async function verifyTelemetry(adapter: PlatformAdapter = new NodePlatformAdapter(), dependencies: TelemetryDependencies = {}): Promise<TelemetryStatus> {
  const config = await readConfig(adapter); if (!config) throw new Error("telemetry-v2 is not configured."); const collector = await readManaged(adapter, "collector"); if (!collector) throw new Error("Collector managed state is missing.");
  const validate = await adapter.run({ executable: collector.command.executable, args: ["validate", "--config", collectorConfigFile(adapter)], timeoutMs: 15_000 }); if (validate.status !== 0) throw new Error("Collector configuration is invalid.");
  const status = await telemetryStatus(adapter, dependencies); if (status.state !== "healthy") throw new Error(`Telemetry verification failed: ${status.state}.`);
  const fetchJson=dependencies.fetchJson??(async(url:string)=>{const parsed=new URL(url);if(parsed.protocol!=="http:"||parsed.hostname!=="127.0.0.1")throw new Error("Telemetry verification is loopback-only.");const response=await fetch(parsed,{signal:AbortSignal.timeout(2_000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.json() as Promise<unknown>;});
  await fetchJson("http://127.0.0.1:13133/");
  const key=await adapter.readText(path.join(root(adapter),"identity.key"));if(!key||!/^[a-f0-9]{64}\s*$/.test(key))throw new Error("Telemetry identity key is unavailable.");const identity=await telemetryIdentity(root(adapter),"afd-canary",Buffer.from(key.trim(),"hex"));const spanId=newSpanId();const now=Date.now();const trace=buildOtlpJsonTrace(identity,[{spanId,name:"agent.run",startedAtUnixMs:now,endedAtUnixMs:now+1,outcome:"ok"}]);addSyntheticPrivacyCanaries(trace);const emit=dependencies.emitTrace??((value:Record<string,unknown>)=>emitLoopbackOtlpJson("http://127.0.0.1:4318/v1/traces",value));let accepted=false;let lastEmitError:unknown;const emittedAt=Date.now();for(let attempt=0;attempt<30&&!accepted;attempt+=1){try{await emit(trace);accepted=true;}catch(error){lastEmitError=error;if(attempt<29)await new Promise(resolve=>setTimeout(resolve,1_000));}}if(!accepted)throw lastEmitError instanceof Error?lastEmitError:new Error("Local OTLP Collector did not accept the synthetic trace.");
  let visibleRow:Record<string,unknown>|undefined;let phoenixQueryMs=0;for(let attempt=0;attempt<40&&!visibleRow;attempt+=1){try{const queryStarted=Date.now();const raw=await fetchJson(`http://127.0.0.1:6006/v1/projects/${encodeURIComponent(identity["afd.project.id"])}/spans/otlpv1?trace_id=${identity.traceId}&limit=10`);phoenixQueryMs=Date.now()-queryStarted;const object=raw&&typeof raw==="object"?raw as Record<string,unknown>:{};const rows=Array.isArray(object.data)?object.data:[];visibleRow=rows.find((item):item is Record<string,unknown>=>Boolean(item)&&typeof item==="object"&&(item as Record<string,unknown>).trace_id===identity.traceId);}catch{/* retry bounded local readiness */}if(!visibleRow)await new Promise(resolve=>setTimeout(resolve,500));}if(!visibleRow)throw new Error("Synthetic span was not visible in Phoenix.");const encoded=JSON.stringify(visibleRow);if(!encoded.includes("afd.outcome"))throw new Error("Phoenix did not expose the synthetic allowlisted control attribute; redaction could not be proven.");if(encoded.includes(PRIVACY_CANARY)||["user.home","prompt","response","file.content","process.command_args","stdout","stderr","custom.secret","forbidden-event"].some(key=>encoded.includes(`"${key}"`)))throw new Error("Synthetic privacy canary survived redaction; rejected categories were not persisted.");const diagnostics:TelemetryDiagnostics={schemaVersion:1,lastVerifiedAt:new Date().toISOString(),redaction:{state:"verified",rejectedCategories:REJECTED_ATTRIBUTE_CATEGORIES},performance:{traceFreshnessMs:Date.now()-emittedAt,phoenixQueryMs}};await adapter.writeText(diagnosticsFile(adapter),JSON.stringify(diagnostics,null,2)+"\n");return{...status,diagnostics};
}
export async function stopTelemetry(adapter: PlatformAdapter = new NodePlatformAdapter(), dependencies: TelemetryDependencies = {}): Promise<void> { const config = await readConfig(adapter); if (config) await (dependencies.agentacct ?? new AgentacctAdapter(adapter, config.capability.agentacct.version)).stop(); await stopManaged(adapter, "collector"); await stopManaged(adapter, "phoenix"); }
export async function resumeTelemetry(adapter: PlatformAdapter = new NodePlatformAdapter(), dependencies: TelemetryDependencies = {}): Promise<TelemetryStatus> { const config=await readConfig(adapter);if(!config)throw new Error("telemetry-v2 is not configured.");const collector=await collectorExecutable(adapter,config.capability);const phoenixData=await wslPath(adapter,path.join(root(adapter),"phoenix","data"));const wslUv=await wslExecutable(adapter,"uv");const phoenixLock=windowsPathToWsl(await verifyPhoenixLock(config.capability));const phoenixPython=await requirePhoenixPython(adapter,config.capability);const phoenixCommand:HostCommand={executable:"wsl.exe",args:["--","env",`PHOENIX_WORKING_DIR=${phoenixData}`,"PHOENIX_TELEMETRY_ENABLED=false","PHOENIX_ALLOW_EXTERNAL_RESOURCES=false",`PHOENIX_DEFAULT_RETENTION_POLICY_DAYS=${config.capability.retentionDays}`,"PHOENIX_ALLOWED_PROVIDERS=NONE","PHOENIX_ALLOWED_SANDBOX_PROVIDERS=NONE",wslUv,"tool","run","--offline","--python",phoenixPython,"--no-python-downloads","--from",`arize-phoenix==${config.capability.phoenix.version}`,"--with-requirements",phoenixLock,"phoenix","serve","--host","127.0.0.1","--port","6006"]};await startManaged(adapter,"phoenix",phoenixCommand);await startManaged(adapter,"collector",{executable:collector,args:["--config",collectorConfigFile(adapter)],cwd:path.join(root(adapter),"collector")});const agentacct=dependencies.agentacct??new AgentacctAdapter(adapter,config.capability.agentacct.version);await agentacct.refresh();await agentacct.start();if(config.capability.autostart){const cli=fileURLToPath(new URL("./cli.js",import.meta.url));await installAutostart(adapter,"telemetry-v2-supervisor",{executable:process.execPath,args:[cli,"telemetry","resume"]});}return waitForHealthyTelemetry(adapter,agentacct); }
export async function uninstallTelemetryAutostart(adapter: PlatformAdapter = new NodePlatformAdapter()): Promise<void> { await uninstallAutostart(adapter, "telemetry-v2-supervisor").catch(() => undefined); }
export async function removeTelemetryManaged(adapter: PlatformAdapter = new NodePlatformAdapter(), dependencies: TelemetryDependencies = {}): Promise<void> { await rollbackNativeIntegrations(adapter);await uninstallTelemetryAutostart(adapter);const config=await readConfig(adapter);const agentacct=dependencies.agentacct??(config?new AgentacctAdapter(adapter,config.capability.agentacct.version):undefined);await stopTelemetry(adapter,dependencies);if(agentacct)await agentacct.uninstallManagedRuntime();if(config)await removePhoenixPython(adapter,config.capability);const managedRoot=path.resolve(root(adapter));const stateRoot=path.resolve(adapter.stateRoot);if(!managedRoot.startsWith(stateRoot+path.sep))throw new Error("Unsafe telemetry managed root.");await rm(managedRoot,{recursive:true,force:true}); }
