import { AgentacctAdapter, type AgentacctSessionEvidence } from "./agentacct-adapter.js";
import path from "node:path";
import type { PlatformAdapter } from "./platform.js";
import { NodePlatformAdapter } from "./platform.js";
import { findTelemetryRun, type TelemetryRunRecord } from "./telemetry-correlation.js";
import { telemetryStatus, type TelemetryStatus } from "./telemetry-runtime.js";

export interface PhoenixTraceEvidence { readonly available: boolean; readonly traceId: string; readonly spanCount?: number; readonly durationMs?: number; readonly status?: string; readonly url: string; readonly detail?: string }
export interface TelemetryExplanation { readonly schemaVersion: 2; readonly status: "complete" | "partial" | "live_only" | "not_found"; readonly runId: string; readonly run?: TelemetryRunRecord; readonly correlation: { readonly status: "exact_session" | "ambiguous" | "unlinked"; readonly basis: readonly string[]; readonly confidence: "exact" | "none" }; readonly phoenix: PhoenixTraceEvidence; readonly agentacct: { readonly available: boolean; readonly evidence?: AgentacctSessionEvidence; readonly detail: string }; readonly health: TelemetryStatus; readonly limitations: readonly string[] }
type JsonFetcher = (url: string) => Promise<unknown>;
const TRACE = /^[a-f0-9]{32}$/;

async function phoenixEvidence(traceId: string, projectId: string | undefined, fetchJson: JsonFetcher): Promise<PhoenixTraceEvidence> {
  const url = "http://127.0.0.1:6006"; if (!projectId) return { available: false, traceId, url, detail: "project identity is unavailable" };
  try { const raw = await fetchJson(`${url}/v1/projects/${encodeURIComponent(projectId)}/traces?include_spans=true&limit=1000`); const object = raw && typeof raw === "object" ? raw as Record<string, unknown> : {}; const data = Array.isArray(object.data) ? object.data : []; const trace = data.find((item) => item && typeof item === "object" && (item as Record<string, unknown>).trace_id === traceId) as Record<string, unknown> | undefined; if (!trace) return { available: false, traceId, url, detail: "trace is not visible in Phoenix" }; const spans = Array.isArray(trace.spans) ? trace.spans : []; const started = typeof trace.start_time === "string" ? Date.parse(trace.start_time) : NaN; const ended = typeof trace.end_time === "string" ? Date.parse(trace.end_time) : NaN; return { available: true, traceId, spanCount: spans.length, ...(Number.isFinite(started) && Number.isFinite(ended) && ended >= started ? { durationMs: ended - started } : {}), ...(typeof trace.status_code === "string" ? { status: trace.status_code } : {}), url }; } catch (error) { return { available: false, traceId, url, detail: error instanceof Error ? error.message : "Phoenix query failed" }; }
}

export async function explainTelemetry(runId: string, adapter: PlatformAdapter = new NodePlatformAdapter(), options: { readonly fetchJson?: JsonFetcher; readonly agentacct?: AgentacctAdapter } = {}): Promise<TelemetryExplanation> {
  if (!TRACE.test(runId)) throw new Error("Run id must be a 32-character lowercase trace id.");
  const fetchJson = options.fetchJson ?? (async (url: string) => { const parsed = new URL(url); if (parsed.protocol !== "http:" || !["127.0.0.1", "localhost", "::1"].includes(parsed.hostname)) throw new Error("Explain queries are restricted to loopback."); const response = await fetch(parsed, { signal: AbortSignal.timeout(2_000) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); return response.json() as Promise<unknown>; });
  const run = await findTelemetryRun(runId, adapter); const [health,phoenix] = await Promise.all([telemetryStatus(adapter, options.agentacct ? { agentacct: options.agentacct } : {}),phoenixEvidence(run?.traceId ?? runId, run?.projectId, fetchJson)]); let evidence:AgentacctSessionEvidence|undefined;let correlation:"exact_session"|"ambiguous"|"unlinked"="unlinked"; let agentacctDetail = health.agentacct.detail;
  if (health.agentacct.state === "healthy" && health.agentacct.version && run?.clientSessionIdHash) { try { const agentacct=options.agentacct ?? new AgentacctAdapter(adapter, health.agentacct.version);const lookup=await agentacct.findBySessionHash(run.agent,run.clientSessionIdHash,path.join(adapter.stateRoot,"telemetry-v2","identity.key"));correlation=lookup.status;if(lookup.status==="exact_session"){evidence=lookup.evidence;agentacctDetail="evidence matched by one trusted client-session link";}else agentacctDetail=lookup.status==="ambiguous"?`multiple exact session candidates (${lookup.matchCount})`:"no exact session evidence";} catch (error) { agentacctDetail = error instanceof Error ? error.message : "agentacct query failed"; } }
  const exact = Boolean(evidence); const found = Boolean(run || phoenix.available || evidence); const status: TelemetryExplanation["status"] = !found ? "not_found" : phoenix.available && evidence ? "complete" : phoenix.available ? "live_only" : "partial"; const limitations: string[] = ["Prompt, response, transcript, file content, command arguments, stdout and stderr are excluded."]; if (!evidence) limitations.push("Session intelligence is unavailable or has no exact trace/session link."); if (!phoenix.available) limitations.push("Phoenix trace evidence is unavailable.");
  return { schemaVersion: 2, status, runId, ...(run ? { run } : {}), correlation: { status: correlation, basis: correlation==="exact_session"?["trusted_session_link","hmac(client,client_session_id)"]:[], confidence: exact ? "exact" : "none" }, phoenix, agentacct: { available: Boolean(evidence), ...(evidence ? { evidence } : {}), detail: agentacctDetail }, health, limitations };
}

export function renderTelemetryExplanation(value: TelemetryExplanation): string { const lines = [`Run ${value.runId}: ${value.status}.`, value.run ? `Observed: ${value.run.agent} ${value.run.outcome}, ${value.run.startedAt} to ${value.run.endedAt}.` : "AFD correlation record: unavailable.", value.phoenix.available ? `Phoenix: ${value.phoenix.spanCount ?? 0} spans, trace visible locally.` : `Phoenix: unavailable (${value.phoenix.detail ?? "unknown"}).`, value.agentacct.available ? `agentacct: ${value.correlation.status}; usage confidence ${value.agentacct.evidence?.usageConfidence ?? "unknown"}; cost confidence ${value.agentacct.evidence?.costConfidence ?? "unknown"}.` : `agentacct: unavailable (${value.agentacct.detail}).`, `Correlation: ${value.correlation.status}; confidence ${value.correlation.confidence}.`, ...value.limitations.map((item) => `Limitation: ${item}`)]; return lines.join("\n"); }
